Svetlana Gavs: Homework 4 completed
eugene-okulik/Svetlana pull request #3
Opened 2024-07-04 21:22 UTC by SvetlanaGavs

2024-07-05 09:22 UTC, eugene-okulik requested changes
Всё отлично, но одну проверку на внимательность не прошла ))

2024-07-05 09:22 UTC, eugene-okulik commented on homework/svetlana_gavrylova/homework_4/task_create_dict.py
> +my_dict['dict']['i am a tuple'] = ('Sometimes', 'I', 'feel', 'like', 'a', 'tuple')
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-07-05 16:29 UTC, SvetlanaGavs commented on homework/svetlana_gavrylova/homework_4/task_create_dict.py
> +my_dict['dict']['i am a tuple'] = ('Sometimes', 'I', 'feel', 'like', 'a', 'tuple')
Поняла! Как-то я наоборот прочитала задание :) ...буду внимательней! Спасибо!

2024-07-07 09:11 UTC, eugene-okulik approved these changes

2024-07-07 09:11 UTC, merged